;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        keyboard-escape-quit
        sp-backward-delete-char
        ))

(setq mc/cmds-to-run-once
      '(
        personal-split-window-horizontally-and-other-window
        sp--self-insert-command
        ))
